module/cpufreq: Warn when cpuinfo doesn't reflect the cpufreq request
ARM-software/devlib pull request #534
Opened 2021-03-30 13:11 UTC by vdonnefort

The cpufreq/scaling_* files reflect the policy configuration from a kernel
point of view. The actual frequency at which the CPU is running can be
found in cpuinfo_cur_freq. Warn when the requested frequency does not
match the actual one.

As the kernel does not provide any guarantee that the requested frequency
will be actually used (due to other part of the system such as thermal or
the firmware), printing a warning instead of raising an error seems more
suitable here.

2021-03-31 09:25 UTC, marcbonnici requested changes

2021-03-31 10:11 UTC, vdonnefort commented on devlib/module/cpufreq.py
> +                    f'The cpufreq value has not been applied properly cpuinfo={cpuinfo} request={value}')
Ack

2021-03-31 10:12 UTC, vdonnefort commented on devlib/module/cpufreq.py
> +            cpuinfo = self.target.read_value(
Unfortunately, get_frequency doesn't return the real frequency, only the one set to the policy.

2021-03-31 10:34 UTC, marcbonnici commented on devlib/module/cpufreq.py
> +            cpuinfo = self.target.read_value(
Ah yes I'd missed the difference. Although thinking about it, would this value be useful to expose as well? Maybe as a flag to `get_frequency`.

2021-04-01 11:28 UTC, marcbonnici approved these changes

2021-04-07 09:55 UTC, merged