Add BackgroundCommand.communicate()
ARM-software/devlib pull request #568
Opened 2021-08-18 16:48 UTC by douglas-raillard-arm

Ease blocking interaction with a BackgroundCommand object, in the style of Popen.communicate()

Tested on paramiko and local target, but not android.

2021-08-18 16:55 UTC, setrofim requested changes
This cannot be merged without the implementation of `communicate()` for all existing derivations of `ConnectionBase` (i.e. `LocalConnection` and `AdbConnection`).

2021-08-18 16:59 UTC, douglas-raillard-arm commented
@setrofim I'm not sure to understand, communicate() is a new method of BackgroundCommand, and is implemented by all its subclasses. ConnectionBase is left untouched in the operation.

2021-08-18 17:06 UTC, setrofim approved these changes
D'oh. My bad. I was fooled by the collapsed code and read it as being added to `ConnectionBase`.  My apologies.

2021-08-18 17:08 UTC, douglas-raillard-arm commented
No worries, GitHub is indeed not so smart in its folding. It only shows the previous "def ..." line in the hunk header, instead of doing something based on indentation

2021-08-19 11:44 UTC, douglas-raillard-arm commented on devlib/connection.py
> +    def communicate(self, input=b'', timeout=None):
Possibly, although it's not requiring overwhelming effort from the caller though:
```
bg.communicate(x.encode())
```
This is also consistent with the fact that stdout and stderr are also bytes.

2021-08-19 11:48 UTC, marcbonnici commented on devlib/connection.py
> +    def communicate(self, input=b'', timeout=None):
Too true, and I guess this way it is consistent with the Popen interface as well.

2021-08-19 11:49 UTC, marcbonnici approved these changes

2021-08-19 11:51 UTC, douglas-raillard-arm commented on devlib/connection.py
> +    def communicate(self, input=b'', timeout=None):
Popen is slightly more refined as it allows specifying an "encoding" and "errors" parameter when creating it. If provided, it's used for stdin/stdout/stderr. So BackgroundCommand is basically behaving like Popen pre-Python 3.6.

2021-08-19 17:32 UTC, merged

2021-08-31 09:30 UTC, douglas-raillard-arm commented
There are a few things to cleanup (docstring etc) so if you are happy with the API as it stands I will proceed with:
* adding docstrings
* renaming asyn.parallel into asyn.concurrently
* remove the `.concurrent` attribute, as it is not that useful in practice I think (it allows running the function concurrently, only blocking to get the result when it is awaited. The "normal" couroutine behavior is to not do anything until the return value is awaited). `asyn.concurrently` is usually better as it makes it obvious what runs concurrently and avoid any kind of "task leak".